package main.model;

public enum Position {
    TRAILING_STOP_COMPLETED_POSITION,
    TAKE_COMPLETED_POSITION,
    STOP_COMPLETED_POSITION,
    SELL_COMPLETED_POSITION,
    BUY_COMPLETED_POSITION,
    TAKE_OR_STOP_POSITION,
    EXAMPLE_POSITION,
    STARTED_POSITION,
}
